// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dyywqphpfkicytcgsthy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImR5eXdxcGhwZmtpY3l0Y2dzdGh5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzM4NzY5MzYsImV4cCI6MjA4OTQ1MjkzNn0.wcED1sFizqGelrdy7175w2EFUeJF09VTc7p9PriTRCo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});